### ISSUE TITLE
Extension initialization failed.

### ISSUE THREAD

**Issue by haomingvince** [jdneo/vscode-leetcode#283]
## 🐛 Bug Report

Cannot initialize the extension.

## To Reproduce

The error message shows when i try to startup the extension.

## Extension Output
v11.14.0
undefined:1

SyntaxError: Unexpected token 
undefined:1

SyntaxError: Unexpected token 
Error: Command "node "C:\Users\[username]\.vscode\extensions\shengchen.vscode-leetcode-0.13.3\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

## Your Environment

- *os*: Windows 10
- *extension settings*:
- *nodejs version*: 11.14.0
- *vscode version*: 1.33.1
- *extension version*: 0.13.3

**Comment by jdneo** [comment]
@haomingvince Could you please try to remove the folder `$HOME/.lc` and to see if the problem still occur?

**Comment by haomingvince** [comment]
It worked! Thank you!

**Comment by gittestjp** [comment]
I got exactly same problem, and there is no $HOME/.1c in my system.
How to fix it?

**Comment by gittestjp** [comment]
Here is log:
v0.12.5
c:\Users\user\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\lib\cli.js:30
  let level = 'INFO';
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\bin\leetcode:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
c:\Users\user\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\lib\cli.js:30
  let level = 'INFO';
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\user\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\bin\leetcode:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Error: Command "node "c:\Users\user\.vscode\extensions\shengchen.vscode-leetcode-0.15.2\node_modules\vsc-leetcode-cli\bin\leetcode",plugin,-i,company" failed with exit code "1".

**Comment by jdneo** [comment]
@gittestjp I think your node version is wrong. Is that `0.12.5`?

**Comment by gittestjp** [comment]
Here is from Windows cmd console:
> node -v
v0.12.5

Is this version too old? I will upgrade to latest version and try it.
Thanks

**Comment by gittestjp** [comment]
It seems working well now. Thanks, If it can detect version of Node.js and pop out more meaningful message, it will be more user friendly.
