### ISSUE TITLE
cannot find module 'github' when submit problem

### ISSUE THREAD

**Issue by zhouchenzc0824** [jdneo/vscode-leetcode#314]
## 🐛 Bug Report

will throw CANNOT FIND MODULE 'github' when submit solution 
testing feature is fine

I can submit my solution via leetcode-cli
 

## To Reproduce
Steps to reproduce the behavior.
Just submit the question, it will throw error

## Extension Output

Paste here the LeetCode extension log from output channel.

Guidance: Press `Ctrl+Shift+U`, and toggle the channel to `LeetCode`.
Expected
  ✔ runtime: 20 ms
  ✔ answer: "1"
  ✔ stdout: ''
/Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/yargs/yargs.js:1148
      else throw err
           ^

Error: Cannot find module 'github'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Plugin.plugin.submitProblem (/Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/plugins/github.js:36:19)
    at /Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/commands/submit.js:57:10
    at /Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:76:45
    at Plugin.plugin.getProblem (/Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:41:14)
    at Plugin.plugin.getProblem (/Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/plugins/solution.discuss.js:75:15)
    at /Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/node_modules/vsc-leetcode-cli/lib/core.js:98:15

## Your Environment

- *os*: mac
- *extension settings*:
- *nodejs version*: v10.15.0
- *vscode version*: 1.33.1
- *extension version*: latest (just reinstalled) 0.14.1

**Comment by jdneo** [comment]
@zhouchenzc0824 Could you please try to remove the entire directory: `/Users/czhou133/.vscode/extensions/shengchen.vscode-leetcode-0.14.1/` and reinstall the extension again?

**Comment by zhouchenzc0824** [comment]
yea thx it worked i have no idea why it was like this coz i never made any changes or update to the extension. LOL

**Comment by jdneo** [comment]
@zhouchenzc0824 maybe the vsix downloaded is corrupted or some IO failure. 

I'm closing this issue since the problem seems to be solved.
