### ISSUE TITLE
Failed to list problem since today, error message from Leetcode CLI

### ISSUE THREAD

**Issue by belovedred1892** [jdneo/vscode-leetcode#347]
/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/yargs/yargs.js:1148
      else throw err
           ^

TypeError: Cannot read property 'toFixed' of null
    at /Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/commands/list.js:76:27
    at /Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/core.js:81:12
    at /Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1183:12
    at Plugin.plugin.getProblems (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:16:12)
    at Plugin.plugin.getProblems (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/plugins/company.js:1171:15)
    at Plugin.core.filterProblems (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/core.js:64:8)
    at Object.cmd.handler (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/vsc-leetcode-cli/lib/commands/list.js:48:8)
    at Object.runCommand (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/yargs/yargs.js:1063:30)
    at Object.get [as argv] (/Users/my_name/.vscode/extensions/shengchen.vscode-leetcode-0.15.0/node_modules/yargs/yargs.js:1004:21)

**Comment by jdneo** [comment]
Hi @belovedred1892,

Please provide more information about your issue to help me repro it, including:
- Which operation are you taking when you meet the problem?
- What's the problem number?
- Which Endpoint are you using?
