### ISSUE TITLE
Cannot show output when the answer is wrong

### ISSUE THREAD

**Issue by SuperCoolSEBoy** [jdneo/vscode-leetcode#414]
## 🐛 Bug Report

Cannot submit

## To Reproduce

Sign in and then submit a solution

## Expected behavior

was working yesterday. But hit this exception tonight.

## Extension Output

- Sending code to judge
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
c:\Users\haoxu\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:267
    x.stdout = util.inspect((result.code_output || []).join('\n'));
                                                       ^

TypeError: (result.code_output || []).join is not a function
    at formatResult (c:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:267:56)
    at Request._callback (c:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:232:16)
    at Request.self.callback (c:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (c:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (c:\Users\xxx\.vscode\extensions\shengchen.vscode-leetcode-0.15.3\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)

## Your Environment

- *os*: Win10
- *extension settings*: default settings
- *nodejs version*: v10.15.3
- *vscode version*: 1.38.1
- *extension version*:0.15.3

**Comment by jdneo** [comment]
What if you remove the folder `$HOME/.vscode/extensions/shengchen.vscode-leetcode-*/` and reinstall the extension?

**Comment by zhiqiyu** [comment]
Encountered the same problem. Reinstall does not solve the problem.

**Comment by jdneo** [comment]
Could you provide the following information to help me diagnostic:
- endpoint you are using
- problem number
- language you are using
- submit or test
- the extension settings (those which are not default values)

**Comment by zhiqiyu** [comment]
Sure.
- Endpoint: LeetCode
- problem #: 142
- Language: Java
- submit or test: submit
- extension settings: 
    - default language: java
    - shortcuts: submit, test, description, solution
    - workspace folder: /myfolder

**Comment by SuperCoolSEBoy** [comment]
Actually..... it no longer repros tonight...the issue is gone...
feel free to close this ticket....and I'll try your solution in case it happens again.

Thanks

**Comment by jdneo** [comment]
I can repro it now. It happens when the answer is wrong. Will fix it in the cli side.
