### ISSUE TITLE
[Help]can't log in leetcode-cn

### ISSUE THREAD

**Issue by zhuanghaixin** [jdneo/vscode-leetcode#431]
This problem occurred when I logged in with email
```
[ERROR] Problem not found!
login: pass: - Signing in leetcode.com
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at args.map.x (/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/log.js:55:31)
    at Array.map (<anonymous>)
    at Object.log.(anonymous function) [as info] (/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/commands/user.js:52:13
    at /Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:77:12
    at /Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:520:14
    at Request._callback (/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:419:19)
    at Request.self.callback (/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/zhuanghaixin/.vscode/extensions/shengchen.vscode-leetcode-0.15.4/node_modules/request/request.js:1161:10)

```

**Comment by jdneo** [comment]
What if you clean the cache folder `$home/.lc`?

**Comment by zhuanghaixin** [comment]
你好，我尝试用rm -rf .lc清除这个文件，还是无法登录，还是出现上面那个报错。然后在leetcode-cn重新建了一个号，可以在vscode上登录。在leetcode.com建了一个号也可以登录。然后我又在其他人的电脑登录，还是不行。但是我在官网上是可以用这个账号登录的
不知道问题出在哪里了。
还有个事，就是我之前在leetcode-cn办过会员，然后会员前几天到期了，不知道和这个有没有关系。
## Your Environment
os:macOS 10.14
extension settings:
nodejs version:v10.10.0
vscode version:1.38.1
extension version:0.15.4

**Comment by jdneo** [comment]
@zhuanghaixin Have you bind your account with your email?

See:

**Comment by Hackergeek** [comment]
pass: - Signing in leetcode-cn.com
- Retrieving user favorites
[WARN] Favorite not found?
- Retrieving user profile
/Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55
      let s = args.map(x => x.toString()).join(' ');
                              ^

TypeError: Cannot read property 'toString' of undefined
    at /Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (/Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/log.js:55:20)
    at /Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:73:13
    at /Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:77:12
    at /Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:529:14
    at Request._callback (/Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:428:19)
    at Request.self.callback (/Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/Users/skyward/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1161:10)

**Comment by hfhg151** [comment]
刚开始用的昵称密码登录，也是报这个错，换了注册的手机号和密码，就登上了。
