### ISSUE TITLE
I need help for this wrong problem

### ISSUE THREAD

**Issue by cheng-lx** [jdneo/vscode-leetcode#434]
## 🐛 Bug Report

   ×      meng-xiang-wei-he    https://leetcode-cn.com
c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\yargs\yargs.js:1148
      else throw err
           ^

TypeError: Cannot read property 'toFixed' of null
    at c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\commands\list.js:76:27
    at c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\core.js:81:12
    at c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\plugins\company.js:1527:12
    at Plugin.plugin.getProblems (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\plugins\cache.js:16:12)
    at Plugin.plugin.getProblems (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\plugins\company.js:1515:15)
    at Plugin.core.filterProblems (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\core.js:64:8)
    at Object.cmd.handler (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\lib\commands\list.js:48:8)
    at Object.runCommand (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\yargs\yargs.js:1063:30)
    at Object.get [as argv] (c:\Users\Halloween\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\yargs\yargs.js:1004:21)

##
i replace the core.js ,because there is a wrong that "No promblem found" when I sign the leetcode. After that It"s still reported, and I don't how to solve it. Can you help me?

## Your Environment

- *os*:win10
- *extension settings*:
- *nodejs version*:12
- *vscode version*:1.38.1
- *extension version*:0.15.4

**Comment by wotaoyanh** [comment]
I got the same problem！
1、Preview problem: 
[ERROR] Problem not found!
2、Show problem:  
Error: Command ""C:\Program Files\nodejs\node.exe" "c:\Users\Administrator\.vscode\extensions\shengchen.vscode-leetcode-0.15.4\node_modules\vsc-leetcode-cli\bin\leetcode",show,1,-c,-l,cpp" failed with exit code "0". Please open the output channel for details.
`[ERROR] Problem not found!`
3、Show top voted solution: 
Failed to fetch the top voted solution. Please open the output channel for details.
`[ERROR] Problem not found!`


```
...
[  4 ] 寻找两个有序数组的中位数                                     Hard   (35.99 %)
[  3 ] 无重复字符的最长子串                                         Medium (31.52 %)
[  2 ] 两数相加                                                     Medium (35.73 %)
[  1 ] 两数之和                                                     Easy   (46.68 %)
[ERROR] Problem not found!
[ERROR] Problem not found!
[ERROR] Problem not found!
```

My Environment
os:win10
extension settings:
nodejs version:12.11.0
vscode version:1.38.1
extension version:0.15.4

help!!!

**Comment by 997282173** [comment]
same problem

```bash
[ERROR] Problem not found!
[ERROR] Problem not found!
[ERROR] Problem not found!
```

**Comment by 997282173** [comment]
[err] Command "node "c:\Users\XXX\Downloads\vscode-leetcode-0.15.3\node_modules\vsc-leetcode-cli\bin\leetcode",show,16,-x" failed with exit code "0".: Error: Command "node "c:\Users\XXX\Downloads\vscode-leetcode-0.15.3\node_modules\vsc-leetcode-cli\bin\leetcode",show,16,-x" failed with exit code "0".

似乎是vsc-leetcode-cli 进程退出了?

**Comment by jdneo** [comment]
Please See: https://github.com/jdneo/vscode-leetcode/issues/430

**Comment by jdneo** [comment]
Is the problem still occur in `0.15.5`?

**Comment by wotaoyanh** [comment]
> Is the problem still occur in `0.15.5`?
No，this problem has been solved
