### ISSUE TITLE
Cannot run Test through extension in LeetCode endpoint

### ISSUE THREAD

**Issue by shanerbo** [jdneo/vscode-leetcode#455]
## updated by @jdneo:

For anyone has this issue, please see https://github.com/jdneo/vscode-leetcode/issues/455#issuecomment-539971863 as a workaround.

---

Keep getting error message:

c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\commands\test.js:93
      results[0].stdout = results[0].stdout.slice(1, -1).replace(/\\n/g, '\n');
                                            ^

TypeError: Cannot read property 'slice' of undefined
    at c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\commands\test.js:93:45
    at _cb (c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\plugins\retry.js:45:21)
    at Queue.onDone (c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:304:14)
    at Queue.workerRun (c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\queue.js:37:12)
    at Immediate.<anonymous> (c:\Users\Erbo\.vscode\extensions\shengchen.vscode-leetcode-0.15.6\node_modules\vsc-leetcode-cli\lib\queue.js:47:36)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by jdneo** [comment]
Please provide Endpoint & problem number

**Comment by sunmiaozju** [comment]
I also meet this problem just now, and it seems like all the problems can not run Test
But also can run submit 
@jdneo

**Comment by yogain123** [comment]
Yes same with me, using the latest version of the extension but still problem exists

**Comment by lintuming** [comment]
@jdneo I found that it seems like this condiction not passed when runing test.
![image](https://user-images.githubusercontent.com/37504587/66466006-86515200-eab4-11e9-8c55-3b779f6df8d5.png)
After i replace the  `interpret` by `runcode`,thoese test work as before .

**Comment by jdneo** [comment]
@lintuming Thank you for investigating. Seems LeetCode changes its response **AGAIN**.

That's what I could not foresee. Will try to update the cli recently

**Comment by tinvaan** [comment]
Sorry to add to the noise guys, but yeah I have the same issue as well :)

```
- Sending code to judge
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
- Waiting for judge result
  ✔ Finished
/home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/commands/test.js:93
      results[0].stdout = results[0].stdout.slice(1, -1).replace(/\\n/g, '\n');
                                            ^

TypeError: Cannot read property 'slice' of undefined
    at /home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/commands/test.js:93:45
    at _cb (/home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/plugins/retry.js:45:21)
    at Queue.onDone (/home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:304:14)
    at Queue.workerRun (/home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/queue.js:37:12)
    at Immediate.<anonymous> (/home/harish/.vscode-oss/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/lib/queue.js:47:36)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by jdneo** [comment]
This bug is because LeetCode updated the content of the response body, so the CLI part is broken.

Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/*⁩` just the same as the [PR](https://github.com/leetcode-tools/leetcode-cli/pull/29) I referenced above.

**Comment by yogain123** [comment]
@jdneo It's working now, Thanks

**Comment by tinvaan** [comment]
> This bug is because LeetCode updated the content of the response body, so the CLI part is broken.
> 
> Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.6/node_modules/vsc-leetcode-cli/*⁩` just the same as the [PR](https://github.com/leetcode-tools/leetcode-cli/pull/29) I referenced above.

Hey just noticed the last release was only 2 days ago. Any idea when you might roll out the next release including this fix?

**Comment by jdneo** [comment]
@tinvaan I've released a new version yesterday.
