### ISSUE TITLE
切换了力扣中国版之后，无法用中国版账号登录

### ISSUE THREAD

**Issue by xiaohuazi123** [jdneo/vscode-leetcode#554]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

Please outline the questions.
选择了力扣中国版，点击登录，点击了登录之后，登录框就消失了
![QQ截图20200518111431](https://user-images.githubusercontent.com/45115671/82171121-f7819f00-98f8-11ea-83c4-60261876afff.jpg)

**Comment by CharlesZHENG** [comment]
中文版，github方式登录，报错如下：
`Cannot read property 'toString' of undefined
    at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\log.js:55:31
    at Array.map (<anonymous>)
    at Object.log.<computed> [as info] (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\log.js:55:20)
    at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\commands\user.js:106:13
    at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14
    at Request._callback (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19)
    at Request.self.callback (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:310:20)`

**Comment by xiaohuazi123** [comment]
> 中文版，github方式登录，报错如下：
> `Cannot read property 'toString' of undefined at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\log.js:55:31 at Array.map (<anonymous>) at Object.log.<computed> [as info] (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\log.js:55:20) at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\commands\user.js:106:13 at c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:529:14 at Request._callback (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\vsc-leetcode-cli\lib\plugins\leetcode.js:428:19) at Request.self.callback (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:185:22) at Request.emit (events.js:310:20) at Request.<anonymous> (c:\Users\YYZ\.vscode\extensions\shengchen.vscode-leetcode-0.16.2\node_modules\request\request.js:1161:10) at Request.emit (events.js:310:20)`

什么？

**Comment by jdneo** [comment]
Please try clean the cache(`$HOME/.lc`) and try again
