### ISSUE TITLE
login: pass: [ERROR] invalid cookie?

### ISSUE THREAD

**Issue by Jackylee1992** [jdneo/vscode-leetcode#619]
## 🐛 Bug Report

Suddenly can not be used for today. Tried for many times, doesn't work.
The console log as follow:
`login: pass: [ERROR] invalid cookie?
/Users/jackylee/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:569
    user.sessionId = cookieData.sessionId;
                                ^

TypeError: Cannot read property 'sessionId' of undefined
    at Request._callback (/Users/jackylee/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:569:33)
    at Request.self.callback (/Users/jackylee/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/jackylee/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/jackylee/.vscode/extensions/leetcode.vscode-leetcode-0.17.0/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

## Your Environment

- *os*:macOS 10.15.6
- *extension settings*:
- *nodejs version*:v12.17.0
- *vscode version*: 1.48
- *extension version*: 0.17.0

**Comment by Helen-Gu** [comment]
Encountered the same issue for leetcode-cn while trying to login using Github account.

**Comment by yihong0618** [comment]
> Encountered the same issue for leetcode-cn while trying to login using Github account.

Yes, please use leetcode-cn account for now, I will have a check maybe today.
