### ISSUE TITLE
SyntaxError: Unexpected string in JSON at position 27

### ISSUE THREAD

**Issue by oceanlvr** [jdneo/vscode-leetcode#66]
I can't log in.
need your help.
v8.12.0
undefined:1
{"cache":true,"retry":true}"leetcode.cn":true}
                           ^

SyntaxError: Unexpected string in JSON at position 27
    at JSON.parse (<anonymous>)
    at Object.cache.get (C:\Users\oyx\.vscode\extensions\shengchen.vscode-leetcode-0.8.0\node_modules\leetcode-cli\lib\cache.js:17:15)
    at Function.Plugin.init (C:\Users\oyx\.vscode\extensions\shengchen.vscode-leetcode-0.8.0\node_modules\leetcode-cli\lib\plugin.js:131:22)
    at Object.cli.run (C:\Users\oyx\.vscode\extensions\shengchen.vscode-leetcode-0.8.0\node_modules\leetcode-cli\lib\cli.js:82:14)
    at Object.<anonymous> (C:\Users\oyx\.vscode\extensions\shengchen.vscode-leetcode-0.8.0\node_modules\leetcode-cli\bin\leetcode:3:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

__

**Comment by oceanlvr** [comment]
@jdneo  Could you please tell me what wrong with it?  thx for your patience. 👍 👍 👍

**Comment by oceanlvr** [comment]
and I try to log with leetcode-cil directly. By using the command:

> Install leetcode cli: npm install -g leetcode-cli
leetcode user -l

 It occurs the same error. And I have no idea what happened.

**Comment by jdneo** [comment]
@oceanlvr Hmm, What's your target login endpoint? Is it `leetcode` or `leetcode.cn`?

**Comment by oceanlvr** [comment]
Thx for your reply.  And I want to log in  **leetcode**
But when I change the endpoint.
An error comes out.

Failed to delete cache. Please open the output channel for details.

**Comment by oceanlvr** [comment]
![image](https://user-images.githubusercontent.com/36698124/45855946-095a1a00-bd85-11e8-8691-a7f7491cbbd9.png)
@jdneo

**Comment by jdneo** [comment]
@oceanlvr Ok. Looks like the json format is wrong. Could you please try to find this file: `C:\Users\[username]\.lc\plugins.json`. And open it.

From your error looks, it looks like the json is wrong: `{"cache":true,"retry":true}"leetcode.cn":true}`.

Try to change it to `{"cache":true,"retry":true,"leetcode.cn":true}` and to see if this could help.

**Comment by oceanlvr** [comment]
@jdneo  Thank you!  I Successfully login.:smile::smile::smile:

**Comment by jdneo** [comment]
@oceanlvr Great. Not quite sure if this is a bug for leetcode-cli. 😄
