### ISSUE TITLE
Login failure with error report: "TypeError:  plugin.next.login is not a function" 

### ISSUE THREAD

**Issue by AilvenLiu** [jdneo/vscode-leetcode#780]
CN endpoint and COM end point were both tried, github and account were both tried. 
All the 4 cases were failed and  error info obtained as following: 

```bash
login: (node:18287) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
pass: /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:89
  plugin.next.login(user, function(e, user) {
              ^

TypeError: plugin.next.login is not a function
    at Plugin.plugin.login (/home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/plugins/cache.js:89:15)
    at /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/vsc-leetcode-cli/lib/commands/user.js:71:12
    at /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:336:32
    at /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/utile/node_modules/async/lib/async.js:154:25
    at assembler (/home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:333:9)
    at /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:342:32
    at /home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/prompt/lib/prompt.js:625:5
    at Interface.onLine (/home/ailven/.vscode/extensions/leetcode.vscode-leetcode-0.18.0/node_modules/read/lib/read.js:111:5)
    at Interface.emit (node:events:526:28)
    at Interface._onLine (node:readline:487:10)
```

**Comment by lllirunze** [comment]
I also have this problem. Anyone can solve this?
