### ISSUE TITLE
windos版 vscode 登录报错

### ISSUE THREAD

**Issue by wymcloud** [jdneo/vscode-leetcode#79]
SyntaxError: Unexpected string in JSON at position 14
    at JSON.parse (<anonymous>)
    at Object.cache.get (C:\Users\wym\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\lib\cache.js:16:15)
    at Function.Plugin.init (C:\Users\wym\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\lib\plugin.js:86:23)
    at initPlugins (C:\Users\wym\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\lib\cli.js:62:14)
    at Object.cli.run (C:\Users\wym\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\lib\cli.js:100:3)
    at Object.<anonymous> (C:\Users\wym\.vscode\extensions\shengchen.vscode-leetcode-0.8.1\node_modules\leetcode-cli\bin\leetcode:3:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
undefined:1
{"cache":true}"retry":true,"leetcode.cn":false}
              ^

**Comment by wymcloud** [comment]
之前 在ubuntu上好使

**Comment by wymcloud** [comment]
能加一下微信或者QQ吗

**Comment by jdneo** [comment]
Close the issue because it has been inactive for a long time.
